use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("emoji_data.rs");

    // Fetch emoji data from jsdelivr
    let url = "https://cdn.jsdelivr.net/npm/emoji-datasource@15.1.2/emoji.json";
    
    let response = ureq::get(url)
        .call()
        .expect("Failed to fetch emoji data");
    
    let json: Vec<EmojiData> = serde_json::from_reader(response.into_body().into_reader())
        .expect("Failed to parse emoji JSON");

    // Filter to only include emojis that have a unified code (actual emoji characters)
    let filtered: Vec<&EmojiData> = json.iter()
        .filter(|e| !e.unified.is_empty())
        .collect();

    // Generate Rust code
    let mut code = String::new();
    code.push_str("/// Auto-generated emoji data from emoji-datasource\n");
    code.push_str("/// DO NOT EDIT - generated by build.rs\n\n");
    code.push_str("use serde::{Deserialize, Serialize};\n\n");
    
    code.push_str("/// Emoji entry from emoji-datasource\n");
    code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    code.push_str("pub struct EmojiEntry {\n");
    code.push_str("    pub unified: &'static str,\n");
    code.push_str("    pub short_name: &'static str,\n");
    code.push_str("    pub category: &'static str,\n");
    code.push_str("}\n\n");
    
    code.push_str("/// Static array of all emojis\n");
    code.push_str("pub static EMOJI_DATA: &[EmojiEntry] = &[\n");
    
    for emoji in filtered {
        let unified = &emoji.unified;
        let short_name = &emoji.short_name;
        let category = &emoji.category;
        
        code.push_str(&format!(
            "    EmojiEntry {{ unified: \"{}\", short_name: \"{}\", category: \"{}\" }},\n",
            escape_str(unified),
            escape_str(short_name),
            escape_str(category)
        ));
    }
    
    code.push_str("];\n\n");
    
    // Add helper function to convert unified code to actual emoji character
    code.push_str("/// Convert unified code (e.g. \"1F600\") to actual emoji character\n");
    code.push_str("pub fn unified_to_emoji(unified: &str) -> String {\n");
    code.push_str("    unified\n");
    code.push_str("        .split('-')\n");
    code.push_str("        .filter_map(|code| u32::from_str_radix(code, 16).ok())\n");
    code.push_str("        .filter_map(char::from_u32)\n");
    code.push_str("        .collect()\n");
    code.push_str("}\n\n");
    
    code.push_str("/// Get a truly random emoji character using rand\n");
    code.push_str("pub fn random_emoji() -> String {\n");
    code.push_str("    use rand::Rng;\n");
    code.push_str("    let mut rng = rand::rng();\n");
    code.push_str("    let idx = rng.random_range(0..EMOJI_DATA.len());\n");
    code.push_str("    unified_to_emoji(EMOJI_DATA[idx].unified)\n");
    code.push_str("}\n");

    fs::write(&dest_path, code).expect("Failed to write emoji_data.rs");
    
    println!("cargo:rerun-if-changed=build.rs");
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\")
     .replace('"', "\\\"")
}

#[derive(serde::Deserialize)]
struct EmojiData {
    unified: String,
    short_name: String,
    category: String,
}
